'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpatialAssetsEnginePlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert GIS vector data to a Ecospace raster with polygon/cell area cell overlap ratios. For this, every cell area / polygon area overlap ratio is calculated, and the ratio [0, 1] is stored in the raster. This method becomes slow for large polygon data sets..
        '''</summary>
        Friend ReadOnly Property CONVERTER_AREARASTER_DESCR() As String
            Get
                Return ResourceManager.GetString("CONVERTER_AREARASTER_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area ratios.
        '''</summary>
        Friend ReadOnly Property CONVERTER_AREARASTER_NAME() As String
            Get
                Return ResourceManager.GetString("CONVERTER_AREARASTER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert GIS vector data to a Ecospace raster using the vector data as a mask, where either values inside or outside the vector data are rasterized..
        '''</summary>
        Friend ReadOnly Property CONVERTER_COOKIECUTTER_DESCR() As String
            Get
                Return ResourceManager.GetString("CONVERTER_COOKIECUTTER_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Masked conversion.
        '''</summary>
        Friend ReadOnly Property CONVERTER_COOKIECUTTER_NAME() As String
            Get
                Return ResourceManager.GetString("CONVERTER_COOKIECUTTER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert GIS raster or polygon data to a value raster compatible with Ecospace. Executed GIS raster operations are Clip and Resample..
        '''</summary>
        Friend ReadOnly Property CONVERTER_DIRECTRASTER_DESCR() As String
            Get
                Return ResourceManager.GetString("CONVERTER_DIRECTRASTER_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raster interpolation.
        '''</summary>
        Friend ReadOnly Property CONVERTER_DIRECTRASTER_NAME() As String
            Get
                Return ResourceManager.GetString("CONVERTER_DIRECTRASTER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert GIS vector data (points, multi-points and polygones) to a pesence/absence raster compatible with Ecospace, where a vector attribute is matched to the name of object in Ecospace.
        '''</summary>
        Friend ReadOnly Property CONVERTER_DIRECTVECTOR_DESCR() As String
            Get
                Return ResourceManager.GetString("CONVERTER_DIRECTVECTOR_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Presence/absence conversion.
        '''</summary>
        Friend ReadOnly Property CONVERTER_DIRECTVECTOR_NAME() As String
            Get
                Return ResourceManager.GetString("CONVERTER_DIRECTVECTOR_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert GIS isobar (height contours) to a Ecospace depth map..
        '''</summary>
        Friend ReadOnly Property CONVERTER_ISOBAR_DESCR() As String
            Get
                Return ResourceManager.GetString("CONVERTER_ISOBAR_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Isobar conversion.
        '''</summary>
        Friend ReadOnly Property CONVERTER_ISOBAR_NAME() As String
            Get
                Return ResourceManager.GetString("CONVERTER_ISOBAR_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A series of ASCII map files, prepared to match a specific Ecospace map size and extent.
        '''</summary>
        Friend ReadOnly Property DATASET_ASCII_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DATASET_ASCII_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A series of Ecospace ASCII files over time.
        '''</summary>
        Friend ReadOnly Property DATASET_ASCII_NAME() As String
            Get
                Return ResourceManager.GetString("DATASET_ASCII_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A series of CSV files in row, col, values* format, as exported by Ecospace. Note that these files lack any spatial reference, and are intended to be used only with the Ecospace scenario from which they were generated..
        '''</summary>
        Friend ReadOnly Property DATASET_CSV_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DATASET_CSV_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A series of Ecospace [row, col, value] CSV files over time.
        '''</summary>
        Friend ReadOnly Property DATASET_CSV_NAME() As String
            Get
                Return ResourceManager.GetString("DATASET_CSV_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A series of spatial time-tagged files.
        '''</summary>
        Friend ReadOnly Property DATASET_MULTIPLE_DESCR() As String
            Get
                Return ResourceManager.GetString("DATASET_MULTIPLE_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A series of spatial files over time.
        '''</summary>
        Friend ReadOnly Property DATASET_MULTIPLE_NAME() As String
            Get
                Return ResourceManager.GetString("DATASET_MULTIPLE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A time-tagged spatial file.
        '''</summary>
        Friend ReadOnly Property DATASET_SINGLE_DESCR() As String
            Get
                Return ResourceManager.GetString("DATASET_SINGLE_DESCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property DATASET_SINGLE_DISPLAYNAME() As String
            Get
                Return ResourceManager.GetString("DATASET_SINGLE_DISPLAYNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A spatial file.
        '''</summary>
        Friend ReadOnly Property DATASET_SINGLE_NAME() As String
            Get
                Return ResourceManager.GetString("DATASET_SINGLE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image files.
        '''</summary>
        Friend ReadOnly Property DIALOGFILTER_IMAGE() As String
            Get
                Return ResourceManager.GetString("DIALOGFILTER_IMAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raster files.
        '''</summary>
        Friend ReadOnly Property DIALOGFILTER_RASTER() As String
            Get
                Return ResourceManager.GetString("DIALOGFILTER_RASTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vector files.
        '''</summary>
        Friend ReadOnly Property DIALOGFILTER_VECTOR() As String
            Get
                Return ResourceManager.GetString("DIALOGFILTER_VECTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to bounds ({0},{1}) to ({2},{3}).
        '''</summary>
        Friend ReadOnly Property FORMAT_BOUNDS() As String
            Get
                Return ResourceManager.GetString("FORMAT_BOUNDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to grid {0}x{1} at {2}°.
        '''</summary>
        Friend ReadOnly Property FORMAT_GRID() As String
            Get
                Return ResourceManager.GetString("FORMAT_GRID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to raster ({0}, {1}, {2}, {3}).
        '''</summary>
        Friend ReadOnly Property FORMAT_RASTER() As String
            Get
                Return ResourceManager.GetString("FORMAT_RASTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to min {0}, max {1}, mean {2}.
        '''</summary>
        Friend ReadOnly Property FORMAT_STATS() As String
            Get
                Return ResourceManager.GetString("FORMAT_STATS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eval.
        '''</summary>
        Friend ReadOnly Property GENERIC_EVAVLUATION() As String
            Get
                Return ResourceManager.GetString("GENERIC_EVAVLUATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registered to {0}.
        '''</summary>
        Friend ReadOnly Property GENERIC_REGISTRATION() As String
            Get
                Return ResourceManager.GetString("GENERIC_REGISTRATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The spatial-temporal data framework requires a valid license to continue.
        '''</summary>
        Friend ReadOnly Property LICENSE_NONE() As String
            Get
                Return ResourceManager.GetString("LICENSE_NONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to registered to {0}.
        '''</summary>
        Friend ReadOnly Property LICENSE_REGISTREE() As String
            Get
                Return ResourceManager.GetString("LICENSE_REGISTREE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracted raster {0}, {1}.
        '''</summary>
        Friend ReadOnly Property OPERATION_EXTRACTRASTER() As String
            Get
                Return ResourceManager.GetString("OPERATION_EXTRACTRASTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vector features extracted by &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property OPERATION_EXTRACTVECTOR() As String
            Get
                Return ResourceManager.GetString("OPERATION_EXTRACTVECTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Projected to {0}.
        '''</summary>
        Friend ReadOnly Property OPERATION_REPROJECT() As String
            Get
                Return ResourceManager.GetString("OPERATION_REPROJECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resampled raster to {0}, {1}.
        '''</summary>
        Friend ReadOnly Property OPERATION_RESAMPLE() As String
            Get
                Return ResourceManager.GetString("OPERATION_RESAMPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One or more files for data set {0} cannot be found. Do you wish to export this data set anyway?.
        '''</summary>
        Friend ReadOnly Property PROMPT_EXPORT_ERROR_NOFILES() As String
            Get
                Return ResourceManager.GetString("PROMPT_EXPORT_ERROR_NOFILES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The data directory &apos;{0}&apos; for data set {1} cannot be found. Do you wish to export this data set anyway?.
        '''</summary>
        Friend ReadOnly Property PROMPT_EXPORT_ERROR_NOPATH() As String
            Get
                Return ResourceManager.GetString("PROMPT_EXPORT_ERROR_NOPATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select spatial-temporal file for &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECTFILE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECTFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select spatial-temporal files for &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECTFILES() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECTFILES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Using converter &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_CONVERTER() As String
            Get
                Return ResourceManager.GetString("STATUS_CONVERTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred loading data. {0}.
        '''</summary>
        Friend ReadOnly Property STATUS_LOAD_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_LOAD_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load ASCII body from &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_LOAD_FAILED_ASCIIBODY() As String
            Get
                Return ResourceManager.GetString("STATUS_LOAD_FAILED_ASCIIBODY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load ASCII header from &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_LOAD_FAILED_ASCIIHEADER() As String
            Get
                Return ResourceManager.GetString("STATUS_LOAD_FAILED_ASCIIHEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load &apos;{0}&apos;, file could not be found.
        '''</summary>
        Friend ReadOnly Property STATUS_LOAD_FILENOTFOUND() As String
            Get
                Return ResourceManager.GetString("STATUS_LOAD_FILENOTFOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skipped loading of file {0}, data already loaded.
        '''</summary>
        Friend ReadOnly Property STATUS_LOAD_SKIPPED() As String
            Get
                Return ResourceManager.GetString("STATUS_LOAD_SKIPPED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loaded data from &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_LOADED() As String
            Get
                Return ResourceManager.GetString("STATUS_LOADED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loaded from cache.
        '''</summary>
        Friend ReadOnly Property STATUS_LOADED_FROM_CACHE() As String
            Get
                Return ResourceManager.GetString("STATUS_LOADED_FROM_CACHE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spatial data {0} does not overlap with Ecospace map.
        '''</summary>
        Friend ReadOnly Property STATUS_NO_OVERLAP() As String
            Get
                Return ResourceManager.GetString("STATUS_NO_OVERLAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} too complex polygon(s) were excluded from automated processing..
        '''</summary>
        Friend ReadOnly Property STATUS_POLYGONSFAILED_COMPLEX() As String
            Get
                Return ResourceManager.GetString("STATUS_POLYGONSFAILED_COMPLEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} invalid polygon(s) were excluded from automated processing..
        '''</summary>
        Friend ReadOnly Property STATUS_POLYGONSFAILED_INVALID() As String
            Get
                Return ResourceManager.GetString("STATUS_POLYGONSFAILED_INVALID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raster data saved to cache at &apos;{0}&apos;..
        '''</summary>
        Friend ReadOnly Property STATUS_RASTER_CACHED() As String
            Get
                Return ResourceManager.GetString("STATUS_RASTER_CACHED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raster data could not be converted. {0}.
        '''</summary>
        Friend ReadOnly Property STATUS_RASTERCONVERSION_EXCEPTION() As String
            Get
                Return ResourceManager.GetString("STATUS_RASTERCONVERSION_EXCEPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This converter can operate on raster data only. Conversion failed..
        '''</summary>
        Friend ReadOnly Property STATUS_VALIDATIONFAILED_RASTERONLY() As String
            Get
                Return ResourceManager.GetString("STATUS_VALIDATIONFAILED_RASTERONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This converter can operate on vector data only. Conversion failed..
        '''</summary>
        Friend ReadOnly Property STATUS_VALIDATIONFAILED_VECTORONLY() As String
            Get
                Return ResourceManager.GetString("STATUS_VALIDATIONFAILED_VECTORONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vector data could not be converted. {0}.
        '''</summary>
        Friend ReadOnly Property STATUS_VECTORCONVERSION_EXCEPTION() As String
            Get
                Return ResourceManager.GetString("STATUS_VECTORCONVERSION_EXCEPTION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
