name: Release NuGet Package
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Use custom NuGet release action
        uses: Official-EwE/Eii.GithubActions/ReleaseNuGetPackageWindows@master
